-- =============================================================================
-- Question forms: add topics column for the M2 5-question-per-topic flow.
--
-- Forms created before M2 carry questions in `questions` (a flat array). Forms
-- generated by the new topic batch flow carry their structure in `topics`:
--
--   [{
--     id: uuid,
--     title: "How you stopped chasing clients",
--     pillar_hint: "storytelling",
--     questions: [
--       { id, input_type: 'scene',          text, placeholder },
--       { id, input_type: 'failed_attempt', text, placeholder },
--       { id, input_type: 'turning_point',  text, placeholder },
--       { id, input_type: 'framework',      text, placeholder },
--       { id, input_type: 'proof',          text, placeholder }
--     ]
--   }]
--
-- The legacy `questions` column stays for backward compat - the submit endpoint
-- routes to the legacy code path when a form has no `topics`.
-- =============================================================================

ALTER TABLE public.question_forms
  ADD COLUMN IF NOT EXISTS topics jsonb NOT NULL DEFAULT '[]'::jsonb;

-- =============================================================================
-- Done.
-- =============================================================================
