-- =============================================================================
-- Content plan slots: the planner's output. One row per planned piece of
-- content (long-form, short-form, engagement reel, carousel) on a client's
-- horizon plan. Stories live in `story_queue_items` instead - they're date-
-- less by default and only land here if explicitly promoted to a date.
--
-- Status flow:
--   planned -> drafted -> approved
-- "approved" is terminal. There's no "posted" state - approval consumes the
-- raw material and marks the slot done from the planner's perspective.
--
-- locked=true survives plan regeneration. Locking is the staff escape hatch
-- when they manually picked a format/material combo and don't want the
-- planner to overwrite it on the next run.
-- =============================================================================

DO $$ BEGIN
  CREATE TYPE public.slot_status AS ENUM ('planned', 'drafted', 'approved');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.slot_stream AS ENUM (
    'long_form',
    'short_form',
    'engagement_reel',
    'carousel'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.content_plan_slots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,

  stream public.slot_stream NOT NULL,

  -- Null only for the long_form stream (long-form has one shape, no format
  -- library). Every other stream points to a row in content_formats.
  format_id uuid REFERENCES public.content_formats(id) ON DELETE SET NULL,

  scheduled_date date NOT NULL,

  status public.slot_status NOT NULL DEFAULT 'planned',

  -- Which topic this slot draws its raw material from. Long-form pulls all
  -- 5 questions from one topic_group_id. Short-form / reels / carousels
  -- usually pick one or two answers from across topics, but the strongest
  -- topic_group_id is recorded here for grouping in the UI.
  topic_group_id uuid,

  -- Specific topic (answer) ids that the format will use. For long-form
  -- this is the 5 ids in input-type order. For shorter formats this is
  -- typically 1-2 ids.
  raw_material_refs jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- ~30-token preview shown on the calendar card. Generated by Flash-Lite
  -- alongside the slot pick so staff see what the slot is "about" before
  -- generating the full script.
  hook_preview text,

  -- Internal scoring breakdown + cooldown state at pick time. Hidden from
  -- the view-only share. Shape:
  --   {
  --     "score": 18.4,
  --     "components": { "material_fit": 8, "coverage_need": 5, ... },
  --     "considered_format_ids": [...],
  --     "skipped": [{ "format_id": "...", "reason": "cooldown" }, ...]
  --   }
  generation_meta jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- FK to a future scripts table (M4). Kept untyped for now; M4 will
  -- formalize the relationship. Storing on the slot keeps the join shallow.
  generated_script_id uuid,

  approved_at timestamptz,
  approved_by uuid REFERENCES public.users(id) ON DELETE SET NULL,

  -- Locked slots survive plan regeneration. The planner skips them and
  -- accounts for their format/bucket when computing coverage for the rest.
  locked boolean NOT NULL DEFAULT false,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS content_plan_slots_client_date_idx
  ON public.content_plan_slots (client_id, scheduled_date);

CREATE INDEX IF NOT EXISTS content_plan_slots_client_status_idx
  ON public.content_plan_slots (client_id, status);

CREATE INDEX IF NOT EXISTS content_plan_slots_topic_group_idx
  ON public.content_plan_slots (topic_group_id) WHERE topic_group_id IS NOT NULL;

DROP TRIGGER IF EXISTS content_plan_slots_set_updated_at ON public.content_plan_slots;
CREATE TRIGGER content_plan_slots_set_updated_at
  BEFORE UPDATE ON public.content_plan_slots
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.content_plan_slots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "content_plan_slots_service_role_all" ON public.content_plan_slots;
CREATE POLICY "content_plan_slots_service_role_all"
  ON public.content_plan_slots FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- =============================================================================
-- Done.
-- =============================================================================
